## configuration for https://travis-ci.org/

language: java

jdk: oraclejdk8

install: mvn clean

script: mvn install

notifications:
  email: true

after_success:
  - bash <(curl -s https://codecov.io/bash)