server:
  port: 18081
spring:
  profiles:
    active: default
  cloud:
    stream:
      bindings:
        msgChannel:
          destination: msg.exchange
          # durable subscription happens only if consumer group is set.
          # see http://docs.spring.io/spring-cloud-stream/docs/1.0.0.RC1/reference/htmlsingle/index.html#durability
          group: msg-group
          consumer:
            max-attempts: 5
      rabbit:
        bindings:
          msgChannel:
            consumer:
              acknowledgeMode: manual
---
spring:
  profiles: default
  cloud:
    stream:
      bindings:
        msgChannel:
          # if you only use one binder you don't have to set the binder.
          # http://docs.spring.io/spring-cloud-stream/docs/current/reference/htmlsingle/#multiple-binders
          binder: rabbit
  rabbitmq:
    host:                                 localhost
    username:                             guest
    password:                             guest
    port:                                 5672

---
spring:
  profiles: docker-rabbitmq
  cloud:
    stream:
      bindings:
        msgChannel:
          binder: rabbit
  rabbitmq:
    host:                                 msg-rabbitmq
    username:                             guest
    password:                             guest
    port:                                 5672
    listener:
      retry:
        enabled: false
---
spring:
  profiles: docker-kafka
  cloud:
    stream:
      kafka:
        binder:
          zkNodes: msg-kafka
          brokers: msg-kafka
      bindings:
        msgChannel:
          binder: kafka